services:
    apache:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/html
        networks:
            - ubi

networks:
    ubi:
        driver: bridge
